#!/bin/bash

rm -f ctags.files
rm -f cscope.in.out
rm -f cscope.out
rm -f cscope.po.out
rm -f tags

if [[ "$1" == "--clean" ]] ; then
  exit 0
fi

find . -name '*.h'    > ./ctags.files
find . -name '*.hpp' >> ./ctags.files
find . -name '*.c'   >> ./ctags.files
find . -name '*.cpp' >> ./ctags.files
find . -name '*.cc'  >> ./ctags.files
ctags --c++-kinds=+p --c-kinds=+p --fields=+iaS --extra=+q -L ctags.files
cscope -b -q ./ctags.files
rm ctags.files
